// Generated by gencpp from file turtle_control/TurtleVel.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROL_MESSAGE_TURTLEVEL_H
#define TURTLE_CONTROL_MESSAGE_TURTLEVEL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_control
{
template <class ContainerAllocator>
struct TurtleVel_
{
  typedef TurtleVel_<ContainerAllocator> Type;

  TurtleVel_()
    : linear(0.0)
    , angular(0.0)  {
    }
  TurtleVel_(const ContainerAllocator& _alloc)
    : linear(0.0)
    , angular(0.0)  {
  (void)_alloc;
    }



   typedef float _linear_type;
  _linear_type linear;

   typedef float _angular_type;
  _angular_type angular;





  typedef boost::shared_ptr< ::turtle_control::TurtleVel_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_control::TurtleVel_<ContainerAllocator> const> ConstPtr;

}; // struct TurtleVel_

typedef ::turtle_control::TurtleVel_<std::allocator<void> > TurtleVel;

typedef boost::shared_ptr< ::turtle_control::TurtleVel > TurtleVelPtr;
typedef boost::shared_ptr< ::turtle_control::TurtleVel const> TurtleVelConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_control::TurtleVel_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_control::TurtleVel_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtle_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'turtle_control': ['/home/alex/Git_Stuff/495/HW1/ws/src/turtle_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtle_control::TurtleVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_control::TurtleVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_control::TurtleVel_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_control::TurtleVel_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_control::TurtleVel_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_control::TurtleVel_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_control::TurtleVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d5c2dcd348ac8f76ce2a4307bd63a13";
  }

  static const char* value(const ::turtle_control::TurtleVel_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d5c2dcd348ac8f7ULL;
  static const uint64_t static_value2 = 0x6ce2a4307bd63a13ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_control::TurtleVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_control/TurtleVel";
  }

  static const char* value(const ::turtle_control::TurtleVel_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_control::TurtleVel_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 linear # linear velocity of turtle\n"
"float32 angular # angular velocity of turtle\n"
;
  }

  static const char* value(const ::turtle_control::TurtleVel_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_control::TurtleVel_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear);
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TurtleVel_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_control::TurtleVel_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_control::TurtleVel_<ContainerAllocator>& v)
  {
    s << indent << "linear: ";
    Printer<float>::stream(s, indent + "  ", v.linear);
    s << indent << "angular: ";
    Printer<float>::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_CONTROL_MESSAGE_TURTLEVEL_H
