# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from turtle_control/VelTranslateRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class VelTranslateRequest(genpy.Message):
  _md5sum = "1f25cc1d17aaca32f6344c8f3ce37b1a"
  _type = "turtle_control/VelTranslateRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Twist TurtleVel

================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['TurtleVel']
  _slot_types = ['geometry_msgs/Twist']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       TurtleVel

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VelTranslateRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.TurtleVel is None:
        self.TurtleVel = geometry_msgs.msg.Twist()
    else:
      self.TurtleVel = geometry_msgs.msg.Twist()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.TurtleVel.linear.x, _x.TurtleVel.linear.y, _x.TurtleVel.linear.z, _x.TurtleVel.angular.x, _x.TurtleVel.angular.y, _x.TurtleVel.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.TurtleVel is None:
        self.TurtleVel = geometry_msgs.msg.Twist()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.TurtleVel.linear.x, _x.TurtleVel.linear.y, _x.TurtleVel.linear.z, _x.TurtleVel.angular.x, _x.TurtleVel.angular.y, _x.TurtleVel.angular.z,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6d().pack(_x.TurtleVel.linear.x, _x.TurtleVel.linear.y, _x.TurtleVel.linear.z, _x.TurtleVel.angular.x, _x.TurtleVel.angular.y, _x.TurtleVel.angular.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.TurtleVel is None:
        self.TurtleVel = geometry_msgs.msg.Twist()
      end = 0
      _x = self
      start = end
      end += 48
      (_x.TurtleVel.linear.x, _x.TurtleVel.linear.y, _x.TurtleVel.linear.z, _x.TurtleVel.angular.x, _x.TurtleVel.angular.y, _x.TurtleVel.angular.z,) = _get_struct_6d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6d = None
def _get_struct_6d():
    global _struct_6d
    if _struct_6d is None:
        _struct_6d = struct.Struct("<6d")
    return _struct_6d
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from turtle_control/VelTranslateResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import turtle_control.msg

class VelTranslateResponse(genpy.Message):
  _md5sum = "1695ba1358130d545c755713e7ca52b4"
  _type = "turtle_control/VelTranslateResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """TurtleVel TurtleVelReturn


================================================================================
MSG: turtle_control/TurtleVel
float32 linear # linear velocity of turtle
float32 angular # angular velocity of turtle
"""
  __slots__ = ['TurtleVelReturn']
  _slot_types = ['turtle_control/TurtleVel']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       TurtleVelReturn

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(VelTranslateResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.TurtleVelReturn is None:
        self.TurtleVelReturn = turtle_control.msg.TurtleVel()
    else:
      self.TurtleVelReturn = turtle_control.msg.TurtleVel()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2f().pack(_x.TurtleVelReturn.linear, _x.TurtleVelReturn.angular))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.TurtleVelReturn is None:
        self.TurtleVelReturn = turtle_control.msg.TurtleVel()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.TurtleVelReturn.linear, _x.TurtleVelReturn.angular,) = _get_struct_2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2f().pack(_x.TurtleVelReturn.linear, _x.TurtleVelReturn.angular))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.TurtleVelReturn is None:
        self.TurtleVelReturn = turtle_control.msg.TurtleVel()
      end = 0
      _x = self
      start = end
      end += 8
      (_x.TurtleVelReturn.linear, _x.TurtleVelReturn.angular,) = _get_struct_2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f = None
def _get_struct_2f():
    global _struct_2f
    if _struct_2f is None:
        _struct_2f = struct.Struct("<2f")
    return _struct_2f
class VelTranslate(object):
  _type          = 'turtle_control/VelTranslate'
  _md5sum = '0b2d8c5b37cf4fe9f75f19f798d7275b'
  _request_class  = VelTranslateRequest
  _response_class = VelTranslateResponse
