// Generated by gencpp from file turtle_control/VelTranslateRequest.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROL_MESSAGE_VELTRANSLATEREQUEST_H
#define TURTLE_CONTROL_MESSAGE_VELTRANSLATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Twist.h>

namespace turtle_control
{
template <class ContainerAllocator>
struct VelTranslateRequest_
{
  typedef VelTranslateRequest_<ContainerAllocator> Type;

  VelTranslateRequest_()
    : twist()  {
    }
  VelTranslateRequest_(const ContainerAllocator& _alloc)
    : twist(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Twist_<ContainerAllocator>  _twist_type;
  _twist_type twist;





  typedef boost::shared_ptr< ::turtle_control::VelTranslateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_control::VelTranslateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VelTranslateRequest_

typedef ::turtle_control::VelTranslateRequest_<std::allocator<void> > VelTranslateRequest;

typedef boost::shared_ptr< ::turtle_control::VelTranslateRequest > VelTranslateRequestPtr;
typedef boost::shared_ptr< ::turtle_control::VelTranslateRequest const> VelTranslateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_control::VelTranslateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_control::VelTranslateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtle_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'turtle_control': ['/home/alex/Git_Stuff/495/sandbox/src/turtle_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtle_control::VelTranslateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_control::VelTranslateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_control::VelTranslateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_control::VelTranslateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_control::VelTranslateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_control::VelTranslateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_control::VelTranslateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a787b2802160dcc7fe02d089e10afe56";
  }

  static const char* value(const ::turtle_control::VelTranslateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa787b2802160dcc7ULL;
  static const uint64_t static_value2 = 0xfe02d089e10afe56ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_control::VelTranslateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_control/VelTranslateRequest";
  }

  static const char* value(const ::turtle_control::VelTranslateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_control::VelTranslateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Twist twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::turtle_control::VelTranslateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_control::VelTranslateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.twist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelTranslateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_control::VelTranslateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_control::VelTranslateRequest_<ContainerAllocator>& v)
  {
    s << indent << "twist: ";
    s << std::endl;
    Printer< ::geometry_msgs::Twist_<ContainerAllocator> >::stream(s, indent + "  ", v.twist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_CONTROL_MESSAGE_VELTRANSLATEREQUEST_H
