#!/usr/bin/env python

# this is the basic shapes node file
# rosrun basic _shapes

import rospy
from visualization_msgs.msg import Marker
rospy.init_node("marker_pub")
marker=Marker()
marker_pub = rospy.Publisher('/visualization_msgs', Marker, queue_size=10)

marker.header.frame_id = "base_link";
#marker.header.stamp = ros::Time();
marker.ns = "my_namespace";
marker.id = 0;
#marker.type = visualization_msgs::Marker::SPHERE;
#marker.action = visualization_msgs::Marker::ADD;
marker.pose.position.x = 1;
marker.pose.position.y = 1;
marker.pose.position.z = 1;
marker.pose.orientation.x = 0.0;
marker.pose.orientation.y = 0.0;
marker.pose.orientation.z = 0.0;
marker.pose.orientation.w = 1.0;
marker.scale.x = 1;
marker.scale.y = 0.1;
marker.scale.z = 0.1;
marker.color.a = 1.0; # Don't forget to set the alpha!
marker.color.r = 0.0;
marker.color.g = 1.0;
marker.color.b = 0.0

marker_pub.publish(marker)
rospy.spin()
